[package]
name = "yoizuki"
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
