[package]
name = "yoizuki"
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-cors = "0.7"
serde = { version = "1.0.201", features = ["serde_derive"] }
validator = "0.18.1"
serde_json = "1.0.117"
futures-util = "0.3.30"
dotenv = "0.15.0"
log = "0.4.21"
env_logger = "0.11.3"
